name: tests
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '12.16.1'
      - name: Install npm dependencies 
        run: npm ci
      - name: Create scope-tags build
        run: npx tsc
      - name: Make temporary folder for tests 
        run: mkdir ./TEST_TMP
      - name: Run Jest unit tests 
        run: npm run test