name: tests
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '12.16.1'
      - run: npm ci
      - run: npx tsc
      - run: npm run test