name: Run Jest tests
run-name: ${{ github.actor }} requested unit tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12.16.1'
      - run: npm ci
      - run: npm run test