name: Run tests and deploy to NPM automatically
on:
  push:
    branches:
      - main
run-name: ${{ github.event.head_commit.message }}
jobs:

  run-tests:
    name: Run unit tests to verifiy package
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check-package-version.outputs.version }}
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          git config --globalc user.name "github-actions[bot]"
          git config --globalc user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: '12.16.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: npm ci
      - name: Create scope-tags build
        run: npx tsc
      # Just to not display git warning in unit test output
      - name: Configure git 
        run: git config --global init.defaultBranch main
      - name: Run Jest unit tests
        run: npm run test
      - name: Check if package should be published
        id: check-package-version
        run: echo "version=$(node ./.github/shouldVersionBePublishedCheck.js)" >> "$GITHUB_OUTPUT"
        shell: bash
  publish:
    name: Publish if package version changed
    needs: run-tests
    runs-on: ubuntu-latest
    if: ${{ needs.run-tests.outputs.version == '1' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '12.16.1'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - name: Create scope-tags build
      run: npx tsc
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: echo ${{needs.run-tests.outputs.version}}
