name: Run tests and deploy to NPM automatically
on: [push]
run-name: ${{ github.event.head_commit.message }}
jobs:

  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '12.16.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: npm install --no-package-lock
      - name: Create scope-tags build
        run: npx tsc
      # Just to not display git warning in unit test output
      - name: Configure git 
        run: git config --global init.defaultBranch main

      - name: Run Jest unit tests 
        run: npm run test

  publish:
    name: Publish
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '12.16.1'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}